name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ubuntu:focall@sha256:c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
      
    steps:
    - name: install stuff
      run: |
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends tzdata keyboard-configuration;
        apt-get install -y bash procps openssl iproute2 curl jq libsnappy-dev net-tools git make gcc g++ wget gnupg libssl-dev;
     
    - name: install erlang
      run: |
        wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | apt-key add -
        echo "deb https://packages.erlang-solutions.com/ubuntu focal contrib" | tee /etc/apt/sources.list.d/erl.list
        apt update
        apt-get install -y erlang
      
    - name: Checkout vernemq
      uses: actions/checkout@v2
      with:
        repository: vernemq/vernemq
        path: .
      
    - name: Compile
      run: make rel
      
    - name: Run tests
      run: rebar3 do eunit, ct
