name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ubuntu:focal
      
    steps:
    - name: install stuff
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata keyboard-configuration
        apt-get -y install bash procps openssl iproute2 curl jq libsnappy-dev net-tools git make gcc g++ wget gnupg libssl-dev
     
    - name: install erlang
      run: |
        wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | apt-key add -
        echo "deb https://packages.erlang-solutions.com/ubuntu focal contrib" | tee /etc/apt/sources.list.d/erl.list
        apt update && apt-get install erlang
      
    - name: Checkout vernemq
      uses: actions/checkout@v2
      with:
        repository: vernemq/vernemq
        path: .
      
    - name: Compile
      run: make rel
      
    - name: Run tests
      run: rebar3 do eunit, ct
