name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - name: Checkout vernemq
      uses: actions/checkout@v2
      with:
        repository: vernemq/vernemq
        path: .
      
    - name: Compile
      run: rebar3 compile
      
    - name: Run tests
      run: rebar3 do eunit, ct
